title: "Tech Notes"
description: "技术笔记与踩坑记录"
baseurl: /blog
url: https://foxlesbiao.github.io
theme: jekyll-theme-cayman
lang: zh-CN
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
